[package]
name = "miden-core"
version = "0.9.1"
description = "Miden VM core components"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
documentation = "https://docs.rs/miden-core/0.9.1"
categories = ["emulators", "no-std"]
keywords = ["instruction-set", "miden", "program"]
edition = "2021"
rust-version = "1.75"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["miden-crypto/std", "math/std", "winter-utils/std"]

[dependencies]
math = { package = "winter-math", version = "0.8", default-features = false }
miden-crypto = { version = "0.9", default-features = false }
winter-utils = { package = "winter-utils", version = "0.9", default-features = false }

[dev-dependencies]
proptest = "1.3"
rand_utils = { version = "0.8", package = "winter-rand-utils" }
